### ISSUE TITLE
Question about SequencingPolicy

### ISSUE THREAD

**Issue by ryukato** [AxonFramework/ReferenceGuide#21]
I found that from the section "Event Publishing & Processing"> "Event Processors" > "Parallel Processing".

> “Is that value is equal for two messages, it means that the messages must be processed sequentially.”

Does above sentence be below one?

> “If that value is equal for two messages, it means that the messages must be processed sequentially?”

and the meaning of the sentence, honestly I don’t get that. I am wondering if the value is equal, then how can determine the order of processing the messages? The messages have same(equal) value,  then which one coming to be processed before the other?

is there any timestamp and it is used to set the order?

Sorry for my bad English, but I will appreciate if you help me understand that.

**Comment by ryukato** [comment]
I think I found the answer by myself. 
> The messages are processed in the order they have been published on the Event bus.

Is that right?

**Comment by smcvb** [comment]
Thanks for pointing out that section @ryukato, it had some typos/non well-formed sentences.
I've adjusted the section you pointed to to the following: 

> If the return value of the `SequencingPolicy` function is equal for two distinct event messages, it means that those messages must be processed sequentially.

This bit does however not pertain the overall ordering of events, which you (I guess) were looking for.
The ordering of the events being given to an Event Processor (the component providing the events to your `@EventHandler` annotated functions) is how they have been published on the bus.

So yes, your last assumption is correct.

And a FYI, for general question about the framework, we usually point to the [Axon Framework Usergroup](https://groups.google.com/forum/#!forum/axonframework) or otherwise Stack Overflow.
So in the case you've got any follow up questions concerning the inner workings of Axon, feel free to post a question there. :-)

**Comment by ryukato** [comment]
Thank you @smcvb.
