### ISSUE TITLE
Add documentation for Aggregate Root instantiation from another Aggregate Root

### ISSUE THREAD

**Issue by smcvb** [AxonFramework/ReferenceGuide#38]
Add documentation for Aggregate Root instantiation from another Aggregate Root with code sample.
See [#354](https://github.com/AxonFramework/AxonFramework/issues/354) for the implementation.

**Comment by fransvanbuul** [comment]
I needed to have some sample code for this, so created it: https://github.com/fransvanbuul/aggregatespawning
May be useful here.

**Comment by mvonrenteln** [comment]
Thank you Frans!

There are still some questions the documentation should answer:
- In which case do I use this feature instead of the regular saga handling? (As I saw everytime an aggregate lifecycle is bound to another aggregate. Or is there more to consider?)
- What exceptions can occur and what is the preferred way to handle it? (Your example does not seem to be production ready here...)
- How is the transaction in this case? It seems that the aggregates share the same transaction?
- How is the case handled if the second aggregate could already exist? (Project the second aggregate? (This could fail anyway because it could be created in the mean time.) Or just catch the Exception Axon throws when it was already created? Or send an event in customer that this this order is created for this customer?) (corresponds to question 2)

I more advanced scenario is: I have an customer aggregate like in the example but I have an aggregate that accumulates the orders monthly and sends a monthly bill to them. Let's say its the Bill aggregate. The bill that I want to add the order to can be already existing or not. Now I can spawn it from the customer. 
But could I send an additional command to the other aggregate in the case the bill already exists and I want to append the order to it?

**Comment by m1l4n54v1c** [comment]
Hi @mvonrenteln,

I'll try to address your concerns.

* A Typical use case of this feature is when you want to create an aggregate as a result of command processing. You could still do it via Saga, but this is an easier way to go since you don't have to create a separate Saga only for the creation of another aggregate.
* An exception that can occur in this case is if something goes wrong during the creation of another aggregate. We are using `AggregateRepository` in order to create a new aggregate (more precisely: `Aggregate<T> newInstance(Callable<T> factoryMethod) throws Exception` method). I suppose this answer the second part of this question: handling of this exception should cover the case of unsuccessful aggregate creation.
* Creation of aggregate is in the same transaction as message handling (although it is highly recommended to create new aggregates from command handlers). 
> It seems that the aggregates share the same transaction?
If by this you refer to the creation of new aggregate only, then it is correct. Otherwise, command handlers in newly created aggregate will have their transactions. (Could be that I didn't understand this question though.)
* I guess that this is answered by the answer to your second question.

Regarding your scenario - Currently, we are always creating a new aggregate, and if one already exists, you'll get an exception. However, we could introduce a new method `createNewIfAbsent(Class<T> aggregateType, Callable<T> factoryMethod)` or `createNewIfAbsent(Class<T> aggregateType, Callable<T> factoryMethod, String newAggregateIdentifier)`. Do you think it would be beneficial? Would like to hear @abuijze / @smcvb opinions on this.

Cheers,
Milan

**Comment by abuijze** [comment]
to add to @m1l4n54v1c's response, you could say that some Aggregates are more decoupled than others. Especially when Aggregates are considered to be in the same bounded context, it is not unthinkable that there are invariants around the creation of an aggregate that are maintained by another.
Examples are always dangerous to give, because there are so many ifs, buts and maybes, so bear with me.
Let's assume we have a Shopping Cart, and when the Cart is confirmed, an Order is created. There is an invariant that you must include at least on product to be able to do that, but also that the maximum amount must be below a predefined value in the Cart. When the Order is created, the Cart is removed (or cleared).
Until now, Axon would require you to use a Saga. This is still an option, especially when you want to keep the Cart and Order very decoupled. Because the Cart has invariants other than just the Cart's contents, the Cart would need to emit an event that like `ReadyForCheckout`, the Saga creates the Order (which emits `OrderCreated`) and then confirms the Cart, which publishes a `CartCleared`.

Now, there is an alternative. The ShoppingCart can check invariants internally, and decide if an Order needs to be created (Order can still check its 'own' rules). In this case, we would only observe the events: `OrderCreated` and `CartCleared`.

As an external observer, the `ReadyForCheckout` event is rather synthetic. It doesn't have real business meaning, but is added to "make it work". In my experience, when different bounded contexts are involved, these in-between events don't tend to be synthetic.

Hope this clarifies our position on the subject.

**Comment by mvonrenteln** [comment]
Thank you @m1l4n54v1c, @abuijze! That makes the usage clearer, thanks!

I think a conditional spawning if the other aggregate does not exist would be very beneficial. In practice I observe aggregates which creation is bound to another aggregate but which are not newly created everytime.
